include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    prefer_final_locals: false
    avoid_print: false
    use_key_in_widget_constructors: false
    prefer_single_quotes: false
    sort_child_properties_last: false
    avoid_unnecessary_containers: false
    prefer_is_empty: false
    prefer_is_not_empty: false
    avoid_relative_lib_imports: false
    always_declare_return_types: false
    annotate_overrides: false
    avoid_empty_else: false
    avoid_init_to_null: false
    avoid_null_checks_in_equality_operators: false
    unnecessary_const: false
    unnecessary_lambdas: false
    unnecessary_new: false
    unnecessary_null_aware_assignments: false
    unnecessary_null_in_if_null_operators: false
    unnecessary_overrides: false
    unnecessary_parenthesis: false
    unnecessary_string_escapes: false
    unnecessary_string_interpolations: false
    unnecessary_this: false
    use_full_hex_values_for_flutter_colors: false
    use_function_type_syntax_for_parameters: false
    use_rethrow_when_possible: false
